apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-daily-dev-tls
  namespace: daily
spec:
  secretName: api-daily-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.daily.dev
  dnsNames:
  - api.daily.dev
  acme:
    config:
    - http01:
        ingress: daily-gateway
      domains:
      - api.daily.dev
